# Using dockerimages ubuntu-vm image it has pre installed ssh agent and a init on /sbin/my_init
# For support watch at phpusin baseimage-docker ubuntu-vm is based on that with some additions
# For internal use 
FROM dockerimages/ubuntu-vm:latest
RUN apt-get -y update && \ 
    apt-get -y -q install \
    apache2 libapache2-mod-passenger && \
    DEBIAN_FRONTEND="noninteractive" && \
    apt-get install -q -y mysql-server mysql-client && \
    service mysql start && echo 'DEBIAN_FRONTEND="noninteractive"' && dpkg-reconfigure redmine << EOF
# automatically generated by the maintainer scripts of redmine/instances/default
# any changes you make will be preserved, though your comments
# will be lost!  to change your settings you should edit this
# file and then run "dpkg-reconfigure /root/redmine/instances/default"

# dbc_install: configure database with dbconfig-common?
#              set to anything but "true" to opt out of assistance
dbc_install='true'

# dbc_upgrade: upgrade database with dbconfig-common?
#              set to anything but "true" to opt out of assistance
dbc_upgrade='true'

# dbc_remove: deconfigure database with dbconfig-common?
#             set to anything but "true" to opt out of assistance
dbc_remove=''

# dbc_dbtype: type of underlying database to use
#	this exists primarily to let dbconfig-common know what database
#	type to use when a package supports multiple database types.  
#	don't change this value unless you know for certain that this
#	package supports multiple database types
dbc_dbtype='mysql'

# dbc_dbuser: database user
#	the name of the user who we will use to connect to the database.
dbc_dbuser='redmine_default'

# dbc_dbpass: database user password
#	the password to use with the above username when connecting
#	to a database, if one is required
dbc_dbpass='SknLaljnCwyg'

# dbc_dbserver: database host.  
#	leave unset to use localhost (or a more efficient local method
#	if it exists).
dbc_dbserver=''

# dbc_dbport: remote database port
#	leave unset to use the default.  only applicable if you are
#	using a remote database.
dbc_dbport=''

# dbc_dbname: name of database
#	this is the name of your application's database.
dbc_dbname='redmine_default'

# dbc_dbadmin: name of the administrative user
#	this is the administrative user that is used to create all of the above
dbc_dbadmin='root'

# dbc_basepath: base directory to hold database files
#	leave unset to use the default.  only applicable if you are
#	using a local (filesystem based) database.    
dbc_basepath=''

##
## postgresql specific settings.  if you don't use postgresql,
## you can safely ignore all of these
##

# dbc_ssl: should we require ssl?
#	set to "true" to require that connections use ssl
dbc_ssl=''

# dbc_authmethod_admin: authentication method for admin
# dbc_authmethod_user: authentication method for dbuser
#	see the section titled "AUTHENTICATION METHODS" in
#	/usr/share/doc/dbconfig-common/README.pgsql for more info
dbc_authmethod_admin=''
dbc_authmethod_user=''

##
## end postgresql specific settings
##
EOF

RUN DEBIAN_FRONTEND="noninteractive" && \
    apt-get install -y -q redmine redmine-mysql 
# redmine(instances)/default

# etc/apache2/mods-available/passenger.conf which needs the text PassengerDefaultUser www-data added as seen here:
RUN cat << EOF > /etc/apache2/mods-available/passenger.conf
<IfModule mod_passenger.c>
  PassengerRoot /usr/lib/ruby/vendor_ruby/phusion_passenger/locations.ini
  PassengerDefaultRuby /usr/bin/ruby
  PassengerDefaultUser www-data
</IfModule>

#<IfModule mod_passenger.c>
#  PassengerDefaultUser www-data
#  PassengerRoot /usr
#  PassengerRuby /usr/bin/ruby
#</IfModule>
EOF

RUN sudo ln -s /usr/share/redmine/public /var/www/redmine && \

RUN cat << EOF > /etc/apache2/sites-available/000-default.conf
<VirtualHost *:80>
	# The ServerName directive sets the request scheme, hostname and port that
	# the server uses to identify itself. This is used when creating
	# redirection URLs. In the context of virtual hosts, the ServerName
	# specifies what hostname must appear in the request's Host: header to
	# match this virtual host. For the default virtual host (this file) this
	# value is not decisive as it is used as a last resort host regardless.
	# However, you must set it for any further virtual host explicitly.
	#ServerName www.example.com

	ServerAdmin webmaster@localhost
	DocumentRoot /var/www/html
	
	<Directory /var/www/redmine>
    RailsBaseURI /redmine
    PassengerResolveSymlinksInDocumentRoot on
          Options Indexes ExecCGI FollowSymLinks
                Order allow,deny
                Allow from all
                AllowOverride all
  </Directory>

	# Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
	# error, crit, alert, emerg.
	# It is also possible to configure the loglevel for particular
	# modules, e.g.
	#LogLevel info ssl:warn

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

	# For most configuration files from conf-available/, which are
	# enabled or disabled at a global level, it is possible to
	# include a line for only one particular virtual host. For example the
	# following line enables the CGI configuration for this host only
	# after it has been globally disabled with "a2disconf".
	#Include conf-available/serve-cgi-bin.conf
</VirtualHost>

<VirtualHost *:80>
        ServerPath /redmin
        DocumentRoot /var/www/redmine
        	<Directory /var/www/redmine>
        	      Options Indexes ExecCGI FollowSymLinks
                Order allow,deny
                Allow from all
                AllowOverride all
      RailsBaseURI /redmine
          PassengerResolveSymlinksInDocumentRoot on
        </Directory>
        
</VirtualHost>
EOF


#RUN cat << EOF > /etc/apache2

CMD /etc/init.d/apache2 start && \
    service mysql start &&\
    /sbin/my_init
# latest dev version
#RUN hg clone https://bitbucket.org/redmine/redmine-trunk redmine
